include _header.mak

########################################
#~ Directory-specific sources/targets ~#
########################################

# This doesn't actually work, but it's a good idea
_EVAL_METRIC := rsqrd

# SRCS := $(_MODULE)/%.foo
# TGTS := $(_MODULE)/%.bar

################################
#~ Directory-specific recipes ~#
################################

#$(_MODULE)/%.bar: $(_MODULE)/%.foo
#	$(_MODULE)/src/script $< $@

include _footer.mak